live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[cursor]
vi_mode_style = "None"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 15

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "Liga SFMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Heavy Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "SemiBold"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/bin/fish"

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
dynamic_title = true
opacity = 0.84
startup_mode = "Windowed"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 0
y = 0
